# Generated by Django 4.2 on 2023-04-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_features_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='features_image',
            new_name='featured_image',
        ),
    ]
